### ISSUE TITLE
size mismatch on model = 'bert-large-uncased'

### ISSUE THREAD

**Issue by Haolin-Yang** [plkmo/BERT-Relation-Extraction#17]
@plkmo I am very impressed with the clean and organized code! It really helps me a lot! 

I have a problem that when I try to run on model size =='bert-large-uncased'. There is a mismatch problem:
Traceback (most recent call last):
  File "D:\BERT\BERT-Relation-Extraction-master\BERTtest.py", line 316, in <module>
    e1_e2_start=e1_e2_start)
  File "C:\Users\qingd\anaconda3\envs\P37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\BERT\BERT-Relation-Extraction-master1\BERT-Relation-Extraction-master\src\model\BERT\modeling_bert.py", line 754, in forward
    classification_logits = self.classification_layer(v1v2)
  File "C:\Users\qingd\anaconda3\envs\P37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\qingd\anaconda3\envs\P37\lib\site-packages\torch\nn\modules\linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\qingd\anaconda3\envs\P37\lib\site-packages\torch\nn\functional.py", line 1369, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [32 x 2048], m2: [1536 x 19] at C:/w/1/s/tmp_conda_3.7_055457/conda/conda-bld/pytorch_1565416617654/work/aten/src\THC/generic/THCTensorMathBlas.cu:273

Could you please give me some clues about how to deal with this problem! 

Thanks a lot!

**Comment by plkmo** [comment]
Thanks, glad it helped. Tensor size wasn't updated in model file. I have updated repo with fix. Please try again

**Comment by Haolin-Yang** [comment]
@plkmo Thank you so much, I also want to make sure the output type is 'Entity mention pooling'  or '[CLS] token' mentioned in the paper? 
Thanks again!

**Comment by plkmo** [comment]
We are using Bert_em, entity markers-entity start representation which gives the best results according to the paper.

**Comment by Haolin-Yang** [comment]
@plkmo Thank you so much!
