### ISSUE TITLE
Missing ./data/BERT_tokenizer.pkl file

### ISSUE THREAD

**Issue by ozbej** [plkmo/BERT-Relation-Extraction#45]
I want to run only the "Fine-tuning on SemEval2010 Task 8" section (main_task.py file). However, I get the following error:
FileNotFoundError: [Errno 2] No such file or directory: './data/BERT_tokenizer.pkl'

Can anyone tell me where I can get this file?

**Comment by ozbej** [comment]
This is the whole stack trace:

Traceback (most recent call last):
  File "main_task.py", line 50, in <module>
    net = train_and_fit(args)
  File "/content/BERT-Relation-Extraction/src/tasks/trainer.py", line 33, in train_and_fit
    train_loader, test_loader, train_len, test_len = load_dataloaders(args)
  File "/content/BERT-Relation-Extraction/src/tasks/preprocessing_funcs.py", line 319, in load_dataloaders
    save_as_pickle("%s_tokenizer.pkl" % model_name, tokenizer)
  File "/content/BERT-Relation-Extraction/src/misc.py", line 22, in save_as_pickle
    with open(completeName, 'wb') as output:
FileNotFoundError: [Errno 2] No such file or directory: './data/BERT_tokenizer.pkl'

**Comment by leonseet** [comment]
You may run `python main_task.py ` with default values first to generate the BERT_tokenizer.pkl

**Comment by ayankhan31** [comment]
I'm trying to run the main_task.py but its showing an error, Can someone explain how and in which order to execute the files?


Traceback (most recent call last):
  File "d:\6th Sem\NLP\Project\BERT-Relation-Extraction-master\main_task.py", line 50, in <module>
    net = train_and_fit(args)
  File "d:\6th Sem\NLP\Project\BERT-Relation-Extraction-master\src\tasks\trainer.py", line 33, in train_and_fit
    train_loader, test_loader, train_len, test_len = load_dataloaders(args)
  File "d:\6th Sem\NLP\Project\BERT-Relation-Extraction-master\src\tasks\preprocessing_funcs.py", line 319, in load_dataloaders
    save_as_pickle("%s_tokenizer.pkl" % model_name, tokenizer)
  File "d:\6th Sem\NLP\Project\BERT-Relation-Extraction-master\src\misc.py", line 22, in save_as_pickle
    with open(completeName, 'wb') as output:
FileNotFoundError: [Errno 2] No such file or directory: './data/BERT_tokenizer.pkl'

**Comment by ayankhan31** [comment]
> 

Still its showing the same error

**Comment by GabrielSoranzoUPEC** [comment]
Requires SemEval2010 Task 8 dataset, available [here.](https://github.com/sahitya0000/Relation-Classification/blob/master/corpus/SemEval2010_task8_all_data.zip) Download & unzip to ./data/ folder.

**Comment by plkmo** [comment]
I have added instructions as suggested to download & unzip the data
