### ISSUE TITLE
Error while Running the files

### ISSUE THREAD

**Issue by ayankhan31** [plkmo/BERT-Relation-Extraction#47]
I'm trying to run the main_task.py but its showing an error, Can someone explain how and in which order to execute the files?

Traceback (most recent call last):
File "d:\6th Sem\NLP\Project\BERT-Relation-Extraction-master\main_task.py", line 50, in
net = train_and_fit(args)
File "d:\6th Sem\NLP\Project\BERT-Relation-Extraction-master\src\tasks\trainer.py", line 33, in train_and_fit
train_loader, test_loader, train_len, test_len = load_dataloaders(args)
File "d:\6th Sem\NLP\Project\BERT-Relation-Extraction-master\src\tasks\preprocessing_funcs.py", line 319, in load_dataloaders
save_as_pickle("%s_tokenizer.pkl" % model_name, tokenizer)
File "d:\6th Sem\NLP\Project\BERT-Relation-Extraction-master\src\misc.py", line 22, in save_as_pickle
with open(completeName, 'wb') as output:
FileNotFoundError: [Errno 2] No such file or directory: './data/BERT_tokenizer.pkl'

**Comment by GabrielSoranzoUPEC** [comment]
Requires SemEval2010 Task 8 dataset, available [here.](https://github.com/sahitya0000/Relation-Classification/blob/master/corpus/SemEval2010_task8_all_data.zip) Download & unzip to ./data/ folder.

**Comment by plkmo** [comment]
I have added instructions as suggested to download & unzip the data
